name: di
version: 3.3.10
authors:
- Vojta Jina <vojta.jina@gmail.com>
- Pavel Jbanov <pavelgj@gmail.com>
- Anting Shen <shenantingtt@gmail.com>
- Misko Hevery <misko@hevery.com>
- Victor Berchet <victor@suumit.com>
description: Dependency Injection framework
homepage: https://github.com/angular/di.dart
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  barback: '>=0.15.0 <0.16.0'
  code_transformers: '^0.5.1'
  path: ">=1.3.0 <2.0.0"
dev_dependencies:
  benchmark_harness: ">=1.0.4 <2.0.0"
  guinness2: '>=0.0.3 <1.0.0'
  matcher: '>=0.11.0 <0.13.0'
  test: '>=0.12.7 <0.13.0'
  transformer_test: '^0.2.1'
transformers:
- di/module_transformer
